name: Flutter CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.1'
          channel: 'stable'

      - name: Install Android SDK Command-Line Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y curl unzip
          curl -o commandlinetools-linux.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          sudo mkdir -p /usr/local/lib/android/sdk/cmdline-tools/latest
          sudo unzip -q commandlinetools-linux.zip -d /usr/local/lib/android/sdk/cmdline-tools/latest
          sudo rm commandlinetools-linux.zip
          echo "ANDROID_HOME=/usr/local/lib/android/sdk" >> $GITHUB_ENV
          echo "PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH" >> $GITHUB_ENV

      - name: Install Android SDK Platform 35
        run: |
          source $GITHUB_ENV
          yes | sdkmanager "platforms;android-35" "build-tools;35.0.0"

      - name: Clean Flutter Build Cache
        run: flutter clean

      - name: Clean Gradle Cache
        run: |
          rm -rf ~/.gradle/caches/
          rm -rf ~/.gradle/wrapper/

      - name: Flutter Version Check
        run: flutter --version

      - name: Install Dependencies
        run: flutter pub get

      - name: Analyze Project
        run: |
          flutter analyze || echo "Analyzer found warnings, but workflow will continue."

      - name: Build APK (Debug)
        run: flutter build apk --debug

      - name: Upload Debug APK Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk