name: Flutter CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.1'
          channel: 'stable'

      - name: Validate Flutter Version
        run: |
          flutter --version | grep "Flutter 3.24.1"

      - name: Install Dependencies
        run: flutter pub get

      - name: Analyze Project
        run: |
          flutter analyze || echo "Analyzer completed with warnings"

      # - name: Run Tests
      #   run: flutter test

      - name: Build APK (Debug)
        run: flutter build apk --debug

      - name: Upload Debug APK Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
