name: Flutter CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.1'
          channel: 'stable'

      - name: Install Android SDK Command-Line Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y curl unzip
          curl -o commandlinetools-linux.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          sudo mkdir -p /usr/local/lib/android/sdk/cmdline-tools
          sudo unzip commandlinetools-linux.zip -d /usr/local/lib/android/sdk/cmdline-tools
          sudo mv /usr/local/lib/android/sdk/cmdline-tools/cmdline-tools /usr/local/lib/android/sdk/cmdline-tools/latest
          sudo rm commandlinetools-linux.zip
          echo "export ANDROID_HOME=/usr/local/lib/android/sdk" >> $GITHUB_ENV
          echo "export PATH=\$ANDROID_HOME/cmdline-tools/latest/bin:\$ANDROID_HOME/platform-tools:\$PATH" >> $GITHUB_ENV
          source $GITHUB_ENV

      - name: Install Android SDK Platform 33
        run: |
          yes | sdkmanager "platforms;android-33" "build-tools;33.0.2"

      - name: Clean Flutter Build Cache
        run: flutter clean

      - name: Flutter Version Check
        run: flutter --version

      - name: Install Dependencies
        run: flutter pub get

      - name: Analyze Project
        run: flutter analyze

      # - name: Run Tests
      #   run: |
      #     if ls test/*.dart 1> /dev/null 2>&1; then
      #       flutter test;
      #     else
      #       echo "No tests found, skipping test step.";
      #     fi

      - name: Build APK (Debug)
        run: flutter build apk --debug

      - name: Upload Debug APK Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
