name: OCR CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.1'
          channel: 'stable'

      - name: Install Android SDK Command-Line Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y curl unzip
          curl -o commandlinetools-linux.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          sudo mkdir -p /usr/local/lib/android/sdk/cmdline-tools/latest
          sudo unzip -q commandlinetools-linux.zip -d /usr/local/lib/android/sdk/cmdline-tools/latest
          sudo rm commandlinetools-linux.zip
          echo "ANDROID_HOME=/usr/local/lib/android/sdk" >> $GITHUB_ENV
          echo "PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH" >> $GITHUB_ENV

      - name: Install Android SDK Platforms and Build Tools
        run: |
          source $GITHUB_ENV
          yes | sdkmanager "platforms;android-34" "build-tools;34.0.0"
          # Install API 35 properly since plugins require it
          yes | sdkmanager "platforms;android-35" "build-tools;35.0.0"

      - name: Downgrade Plugin Dependencies if Needed
        run: |
          # Modify pubspec.yaml to use compatible plugin versions if needed
          if grep -q "flutter_plugin_android_lifecycle" pubspec.yaml; then
            # Option to pin the plugin to a version compatible with API 34
            echo "Note: Consider pinning flutter_plugin_android_lifecycle version in pubspec.yaml if builds fail"
          fi

      - name: Update Gradle Config for SDK Compatibility
        run: |
          # Ensure compileSdk is set correctly in build.gradle
          if [ -f "android/app/build.gradle" ]; then
            sed -i 's/compileSdkVersion = 34/compileSdkVersion = 35/g' android/app/build.gradle
            sed -i 's/compileSdkVersion 34/compileSdkVersion 35/g' android/app/build.gradle
            sed -i 's/targetSdk = 34/targetSdk = 35/g' android/app/build.gradle
            sed -i 's/targetSdkVersion 34/targetSdkVersion 35/g' android/app/build.gradle
          fi

      - name: Clean Flutter Build Cache
        run: flutter clean

      - name: Clean Gradle Cache
        run: |
          rm -rf ~/.gradle/caches/
          rm -rf ~/.gradle/wrapper/

      - name: Flutter Version Check
        run: flutter --version

      - name: Install Dependencies
        run: flutter pub get

      - name: Analyze Project
        run: |
          flutter analyze || echo "Analyzer found warnings, but workflow will continue."

      - name: Build APK (Debug)
        run: flutter build apk --debug

      - name: Upload Debug APK Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk